apiVersion: apps/v1
kind: Deployment
metadata:
  name: compensation
  labels:
    app: compensation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compensation
  template:
    metadata:
      labels:
        app: compensation
    spec:
      containers:
        - name: compensation
          image: kimkyusoo/compensation:0603
          ports:
            - containerPort: 8080
