name: Build and Push Services

on:
  push:
    tags:
      - v*

jobs:
  build-accident:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Project for Accident
        run: mvn clean package -f ./accident/pom.xml

      - name: Docker Build and push for Accident
        uses: docker/build-push-action@v4
        with:
          context: ./accident
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/kyusook/egov-uengine/accident:${{ github.sha }}

  build-assessment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Project for Assessment
        run: mvn clean package -f ./assessment/pom.xml

      - name: Docker Build and push for Assessment
        uses: docker/build-push-action@v4
        with:
          context: ./assessment
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/kyusook/egov-uengine/assessment:${{ github.sha }}

  build-compensation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Project for Compensation
        run: mvn clean package -f ./compensation/pom.xml

      - name: Docker Build and push for Compensation
        uses: docker/build-push-action@v4
        with:
          context: ./compensation
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/kyusook/egov-uengine/compensation:${{ github.sha }}

  build-gateway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Project for gateway
        run: mvn clean package -f ./gateway/pom.xml

      - name: Docker Build and push for gateway
        uses: docker/build-push-action@v4
        with:
          context: ./compensation
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/kyusook/egov-uengine/gateway:${{ github.sha }}

  build-egov-default-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Project for egov-default-backend
        run: mvn clean package -f ./egov-default-backend/pom.xml

      - name: Docker Build and push for egov-default-backend
        uses: docker/build-push-action@v4
        with:
          context: ./egov-default-backend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/kyusook/egov-uengine/egov-default-backend:${{ github.sha }}