name: CI to Docker Hub

on:
  push:
    branches: [ main ]

env:
  DOCKERHUB_USERNAME: kimkyusoo
  DOCKERHUB_PASSWORD: Rlarbtn135!

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./accident/pom.xml
          mvn clean package -f ./assessment/pom.xml
          mvn clean package -f ./compensation/pom.xml
          mvn clean package -f ./statistics/pom.xml
          mvn clean package -f ./notification/pom.xml

      - name: Docker Build and push for Accident
        uses: docker/build-push-action@v4
        with:
          context: ./accident
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/kyusook/egov-uengine/accident:latest
            ghcr.io/kyusook/egov-uengine/accident:${{ github.ref_name }}
            
      - name: Docker Build and push for Assessment
        uses: docker/build-push-action@v4
        with:
          context: ./assessment
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/kyusook/egov-uengine/assessment:latest
            ghcr.io/kyusook/egov-uengine/assessment:${{ github.ref_name }}
            
      - name: Docker Build and push for Compensation
        uses: docker/build-push-action@v4
        with:
          context: ./compensation
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/kyusook/egov-uengine/compensation:latest
            ghcr.io/kyusook/egov-uengine/compensation:${{ github.ref_name }}